### ISSUE TITLE
Which version is deployed?

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/cougar_4x_refactor#1]
Natty, can you please confirm that this is the version deployed at http://cougar.codefornature.org?

I am doing some housekeeping.

Thank you very much, 
Falk

**Comment by nathanielrindlaub** [comment]
Hey @postfalk, no this was very early experiment/attempt at trying to rebuild the current Cougar app with the 4.x api. The 3.x cougar app repo is (here)[https://github.com/tnc-ca-geo/cougar]. 

We could actually delete this repo. If we ever rebuild the full Cougar app I would start from scratch.
